### ISSUE TITLE
Allow rules to specify egress cidr to allow egress from multiple nodes.

### ISSUE THREAD

**Issue by captncraig** [nirmata/kube-static-egress-ip#17]
Right now a director is required because a single static egress IP is desired. The downside being the director itself is a point of failure. What if there is a situation where I would rather have traffic go out from whatever node the source pod is on, and am less picky about the specific IP.

In my case, each kube node has multiple interfaces available. All egress traffic by default will go out as the public IP address calico is managing, but particular services I would like to use a secondary range.

What if the `StaticEgressIP` crd allowed a cidr instead of a single IP?

```
apiVersion: staticegressips.nirmata.io/v1alpha1
kind: StaticEgressIP
metadata:
  name: eip
spec:
  rules:
  - egresscidr: 100.137.146.0/24
    service-name: frontend
    cidr: 4.2.2.2/32
```

The routing rules would then be a bit simpler:

- If the local node has an interface with a matching IP, send traffic from the `frontend` pods to the destination cidr on that interface.
- If not, forward to the director as before.

I feel like such a solution could be a fairly painless way to relax the requirement of a single director for most traffic in some environments.

Does this seem like a possibility?
