### ISSUE TITLE
No clean-up when the egressip service is removed

### ISSUE THREAD

**Issue by uablrek** [nirmata/kube-static-egress-ip#23]
When the service defined by `service-name:` in the `StaticEgressIP` is removed nothing is cleaned up. The egress-ip function remains fully operable.

Here is the manifest used;
```
apiVersion: v1
kind: Service
metadata:
  name: egressip-alpine
spec:
  selector:
    app: alpine
  ports:
  - name: probe
    port: 5001
---
apiVersion: staticegressips.nirmata.io/v1alpha1
kind: StaticEgressIP
metadata:
  name: egressip-alpine
spec:
  rules:
  - egressip: 15.0.0.13
    service-name: egressip-alpine
    cidr: 192.168.2.0/24
```

Then the service is removed with;
```
kubectl delete svc egressip-alpine
```
